version: '3.1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data:/data/customer
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
